# 项目相关配置
wolves:
  # 名称
  name: Wolves
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/wolves/uploadPath，Linux配置 /home/wolves/uploadPath）
  profile: ${user.dir}/filePath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
server:
  port: 8090
  error:
    include-message: always
spring:

  output:
    #控制台彩色输出
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #MySql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.175.65.121:3306/work_test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: nb
    password: nb9901001

#mybatis-plus配置
mybatis-plus:
  configuration:
    #控制台打印日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl


logging:
  level:
    run.wolves: INFO
    org.eclipse.jetty.server.HttpChannel: ERROR
  file:
    path: ${monomer.work-dir}/logs

monomer:
  download-timeout: 5m
  cache: memory
  work-dir: ${user.home}/.monomer/

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /